# Generated by Django 5.2.10 on 2026-01-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
